# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_author',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='book_author',
            name='book_id',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='Authors', to='book_authors.Book'),
        ),
        migrations.DeleteModel(
            name='Book_Author',
        ),
    ]
